version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mytestdb
      SPRING_DATASOURCE_USERNAME: mytestdb
      SPRING_DATASOURCE_PASSWORD: mytestdb
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mytestdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mytestdb'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mytestdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3406:3306'
    expose:
      # Opens port 3306 on the container
      - '3406'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
